\c fake-it

DROP TABLE IF EXISTS words;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE words (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  category VARCHAR(64) NOT NULL,
  word VARCHAR(64) NOT NULL
);

INSERT INTO words (category, word)
  VALUES ('Cartoon Animals', 'Garfield'),
  ('Cartoon Animals', 'Scooby-Doo'),
  ('Cartoon Animals', 'Yogi Bear'),
  ('Cartoon Animals', 'Bugs Bunny'),
  ('Cartoon Animals', 'Mickey Mouse'),
  ('Cartoon Animals', 'Goofy'),
  ('Cartoon Animals', 'Jiminy Cricket'),
  ('Cartoon Animals', 'Kung Fu Panda'),
  ('Cartoon Animals', 'Nemo'),
  ('Cartoon Animals', 'Tony the Tiger'),
  ('Cartoon Animals', 'Snoopy'),
  ('Cartoon Animals', 'Bambi'),
  ('Cartoon Animals', 'Dumbo'),
  ('Cartoon Animals', 'Wile E. Coyote'),
  ('Cartoon Animals', 'Simba'),
  ('Cartoon Animals', 'Sonic the Hedgehog'),
  ('Children''s Books', 'The Hobbit'),
  ('Children''s Books', 'Peter Pan'),
  ('Children''s Books', 'The Very Hungry Caterpillar'),
  ('Children''s Books', '101 Dalmatians'),
  ('Children''s Books', 'Matilda'),
  ('Children''s Books', 'Harry Potter & The Sorcerer''s Stone'),
  ('Children''s Books', 'Alice in Wonderland'),
  ('Children''s Books', 'The Lion, the Witch, and the Wardrobe'),
  ('Children''s Books', 'Stuart Little'),
  ('Children''s Books', 'Goodnight Moon'),
  ('Children''s Books', 'Charlie and the Chocolate Factory'),
  ('Children''s Books', 'Where the Wild Things Are'),
  ('Children''s Books', 'Winnie-the-Pooh'),
  ('Children''s Books', 'The Adventures of Tom Sawyer'),
  ('Children''s Books', 'The Jungle Book'),
  ('Children''s Books', 'Charlotte''s Web'),
  ('Cities', 'New York City'),
  ('Cities', 'Moscow'),
  ('Cities', 'Delhi'),
  ('Cities', 'London'),
  ('Cities', 'Paris'),
  ('Cities', 'Rome'),
  ('Cities', 'Rio de Janerio'),
  ('Cities', 'Sydney'),
  ('Cities', 'Tokyo'),
  ('Cities', 'Athens'),
  ('Cities', 'Cairo'),
  ('Cities', 'Hong Kong'),
  ('Cities', 'Chicago'),
  ('Cities', 'L.A'),
  ('Cities', 'San Francisco'),
  ('Cities', 'Jerusalem'),
  ('Countries', 'UK'),
  ('Countries', 'Spain'),
  ('Countries', 'Japan'),
  ('Countries', 'Brazil'),
  ('Countries', 'France'),
  ('Countries', 'USA'),
  ('Countries', 'Italy'),
  ('Countries', 'Australia'),
  ('Countries', 'Germany'),
  ('Countries', 'Mexico'),
  ('Countries', 'India'),
  ('Countries', 'Israel'),
  ('Countries', 'Canada'),
  ('Countries', 'China'),
  ('Countries', 'Russia'),
  ('Countries', 'Egypt'),
  ('Desserts', 'Ice Cream'),
  ('Desserts', 'Chocolate'),
  ('Desserts', 'Brownies'),
  ('Desserts', 'Cookies'),
  ('Desserts', 'Cake'),
  ('Desserts', 'Cheesecake'),
  ('Desserts', 'Fudge'),
  ('Desserts', 'Pie'),
  ('Desserts', 'Cobbler'),
  ('Desserts', 'Tiramisu'),
  ('Desserts', 'S''mores'),
  ('Desserts', 'Cupcakes'),
  ('Desserts', 'Lemon Bars'),
  ('Desserts', 'Peanut Brittle'),
  ('Desserts', 'Toffee'),
  ('Desserts', 'Rice Krispie Treats'),
  ('Drinks', 'Coffee'),
  ('Drinks', 'Tea'),
  ('Drinks', 'Lemonade'),
  ('Drinks', 'Coca-Cola'),
  ('Drinks', 'Wine'),
  ('Drinks', 'Beer'),
  ('Drinks', 'Punch'),
  ('Drinks', 'Tequila'),
  ('Drinks', 'Hot Chocolate'),
  ('Drinks', 'Milkshake'),
  ('Drinks', 'Root Beer'),
  ('Drinks', 'Water'),
  ('Drinks', 'Smoothie'),
  ('Drinks', 'Orange Juice'),
  ('Drinks', 'Milk'),
  ('Drinks', 'Champagne'),
  ('Fairy Tales', 'Cinderella'),
  ('Fairy Tales', 'Goldilocks'),
  ('Fairy Tales', 'Jack and the Beanstalk'),
  ('Fairy Tales', 'Hare and the Tortoise'),
  ('Fairy Tales', 'Snow White'),
  ('Fairy Tales', 'Rapunzel'),
  ('Fairy Tales', 'Aladdin'),
  ('Fairy Tales', 'Robin Hood'),
  ('Fairy Tales', 'Peter Pan'),
  ('Fairy Tales', 'Little Red Riding Hood'),
  ('Fairy Tales', 'Pinocchio'),
  ('Fairy Tales', 'Beauty and the Beast'),
  ('Fairy Tales', 'Sleeping Beauty'),
  ('Fairy Tales', 'Hansel and Gretel'),
  ('Fairy Tales', 'Gingerbread Man'),
  ('Fairy Tales', 'Three Little Pigs'),
  ('Fictional Characters', 'Indiana Jones'),
  ('Fictional Characters', 'Mary Poppins'),
  ('Fictional Characters', 'Spiderman'),
  ('Fictional Characters', 'Catwoman'),
  ('Fictional Characters', 'James Bond'),
  ('Fictional Characters', 'Wonder Woman'),
  ('Fictional Characters', 'Princess Leia'),
  ('Fictional Characters', 'The Little Mermaid'),
  ('Fictional Characters', 'Dracula'),
  ('Fictional Characters', 'Mickey Mouse'),
  ('Fictional Characters', 'Robin Hood'),
  ('Fictional Characters', 'Hermione Granger'),
  ('Fictional Characters', 'Super Mario'),
  ('Fictional Characters', 'Homer Simpson'),
  ('Fictional Characters', 'Hercules'),
  ('Fictional Characters', 'Katniss Everdeen'),
  ('Film Genres', 'Horror'),
  ('Film Genres', 'Action'),
  ('Film Genres', 'Thriller'),
  ('Film Genres', 'Sci-Fi'),
  ('Film Genres', 'Rom-Com'),
  ('Film Genres', 'Western'),
  ('Film Genres', 'Comedy'),
  ('Film Genres', 'Christmas'),
  ('Film Genres', 'Gangster'),
  ('Film Genres', 'Foreign Language'),
  ('Film Genres', 'War'),
  ('Film Genres', 'Documentary'),
  ('Film Genres', 'Musical'),
  ('Film Genres', 'Animation'),
  ('Film Genres', 'Zombie'),
  ('Film Genres', 'Sport'),
  ('Food', 'Pizza'),
  ('Food', 'Potatoes'),
  ('Food', 'Fish'),
  ('Food', 'Cake'),
  ('Food', 'Pasta'),
  ('Food', 'Salad'),
  ('Food', 'Soup'),
  ('Food', 'Bread'),
  ('Food', 'Eggs'),
  ('Food', 'Cheese'),
  ('Food', 'Fruit'),
  ('Food', 'Chicken'),
  ('Food', 'Sausage'),
  ('Food', 'Ice Cream'),
  ('Food', 'Chocolate'),
  ('Food', 'Beef'),
  ('Games', 'Monopoly'),
  ('Games', 'Scrabble'),
  ('Games', 'Mouse Trap'),
  ('Games', 'Guess Who'),
  ('Games', 'Risk'),
  ('Games', 'Operation'),
  ('Games', 'Twister'),
  ('Games', 'Pictionary'),
  ('Games', 'Battleship'),
  ('Games', 'Sudoku'),
  ('Games', 'Clue'),
  ('Games', 'Chess'),
  ('Games', 'Checkers'),
  ('Games', 'Trivial Pursuit'),
  ('Games', 'Jenga'),
  ('Games', 'Hungry Hungry Hippos'),
  ('Geography', 'Lake'),
  ('Geography', 'Sea'),
  ('Geography', 'Valley'),
  ('Geography', 'Mountain'),
  ('Geography', 'River'),
  ('Geography', 'Desert'),
  ('Geography', 'Ocean'),
  ('Geography', 'Forest'),
  ('Geography', 'Jungle'),
  ('Geography', 'Island'),
  ('Geography', 'Glacier'),
  ('Geography', 'Waterfall'),
  ('Geography', 'Volcano'),
  ('Geography', 'Cave'),
  ('Geography', 'Arctic'),
  ('Geography', 'Swamp'),
  ('Hobbies', 'Stamps'),
  ('Hobbies', 'Trains'),
  ('Hobbies', 'Model Making'),
  ('Hobbies', 'Knitting'),
  ('Hobbies', 'Fishing'),
  ('Hobbies', 'Reading'),
  ('Hobbies', 'Painting'),
  ('Hobbies', 'Gardening'),
  ('Hobbies', 'Sailing'),
  ('Hobbies', 'Travel'),
  ('Hobbies', 'Walking'),
  ('Hobbies', 'Pottery'),
  ('Hobbies', 'Cooking'),
  ('Hobbies', 'Yoga'),
  ('Hobbies', 'Photography'),
  ('Hobbies', 'Hiking'),
  ('Inventions', 'Matches'),
  ('Inventions', 'Gunpowder'),
  ('Inventions', 'Wheel'),
  ('Inventions', 'Printing'),
  ('Inventions', 'Computer'),
  ('Inventions', 'Internet'),
  ('Inventions', 'Compass'),
  ('Inventions', 'Plane'),
  ('Inventions', 'TV'),
  ('Inventions', 'Electricity'),
  ('Inventions', 'Writing'),
  ('Inventions', 'Steam Engine'),
  ('Inventions', 'Car'),
  ('Inventions', 'Telephone'),
  ('Inventions', 'Camera'),
  ('Inventions', 'Radio'),
  ('Jobs', 'Fisherman'),
  ('Jobs', 'Lumberjack'),
  ('Jobs', 'Nurse'),
  ('Jobs', 'Waiter'),
  ('Jobs', 'Janitor'),
  ('Jobs', 'Secretary'),
  ('Jobs', 'Accountant'),
  ('Jobs', 'Teacher'),
  ('Jobs', 'Truck Driver'),
  ('Jobs', 'Security Guard'),
  ('Jobs', 'Chef'),
  ('Jobs', 'Architect'),
  ('Jobs', 'Software Engineer'),
  ('Jobs', 'Lawyer'),
  ('Jobs', 'Carpenter'),
  ('Jobs', 'Butcher'),
  ('Movies', 'Jurassic Park'),
  ('Movies', 'Jaws'),
  ('Movies', 'Raiders of the Lost Ark'),
  ('Movies', 'The Avengers'),
  ('Movies', 'Transformers'),
  ('Movies', 'Toy Story'),
  ('Movies', 'Home Alone'),
  ('Movies', 'Titanic'),
  ('Movies', 'E.T.'),
  ('Movies', 'The Wizard of Oz'),
  ('Movies', 'King Kong'),
  ('Movies', 'Legally Blonde'),
  ('Movies', 'Shrek'),
  ('Movies', 'Princess Diaries'),
  ('Movies', 'Finding Nemo'),
  ('Movies', 'Avatar'),
  ('Music', 'Rock'),
  ('Music', 'Heavy Metal'),
  ('Music', 'Classical'),
  ('Music', 'Funk'),
  ('Music', 'Hip Hop'),
  ('Music', 'Pop'),
  ('Music', 'Techno'),
  ('Music', 'Blues'),
  ('Music', 'Rap'),
  ('Music', 'Punk'),
  ('Music', 'Indie'),
  ('Music', 'Christmas'),
  ('Music', 'Country'),
  ('Music', 'House'),
  ('Music', 'Disco'),
  ('Music', 'Reggae'),
  ('Musical Instruments', 'Electric Guitar'),
  ('Musical Instruments', 'Piano'),
  ('Musical Instruments', 'Violin'),
  ('Musical Instruments', 'Drums'),
  ('Musical Instruments', 'Bass Guitar'),
  ('Musical Instruments', 'Saxophone'),
  ('Musical Instruments', 'Cello'),
  ('Musical Instruments', 'Flute'),
  ('Musical Instruments', 'Clarinet'),
  ('Musical Instruments', 'Trumpet'),
  ('Musical Instruments', 'Voice'),
  ('Musical Instruments', 'Ukulele'),
  ('Musical Instruments', 'Harp'),
  ('Musical Instruments', 'Bagpipes'),
  ('Musical Instruments', 'Harmonica'),
  ('Musical Instruments', 'Banjo'),
  ('Mythical Creatures', 'Cyclops'),
  ('Mythical Creatures', 'Pegasus'),
  ('Mythical Creatures', 'Medusa'),
  ('Mythical Creatures', 'Sphinx'),
  ('Mythical Creatures', 'Werewolf'),
  ('Mythical Creatures', 'Unicorn'),
  ('Mythical Creatures', 'Dragon'),
  ('Mythical Creatures', 'Troll'),
  ('Mythical Creatures', 'Loch Ness Monster'),
  ('Mythical Creatures', 'Mermaid'),
  ('Mythical Creatures', 'Phoenix'),
  ('Mythical Creatures', 'Vampire'),
  ('Mythical Creatures', 'Minotaur'),
  ('Mythical Creatures', 'Hydra'),
  ('Mythical Creatures', 'Yeti'),
  ('Mythical Creatures', 'Centaur'),
  ('Pets', 'Dog'),
  ('Pets', 'Cat'),
  ('Pets', 'Fish'),
  ('Pets', 'Guinea Pig'),
  ('Pets', 'Parakeet'),
  ('Pets', 'Ferret'),
  ('Pets', 'Sugar Glider'),
  ('Pets', 'Hermit Crab'),
  ('Pets', 'Parrot'),
  ('Pets', 'Snake'),
  ('Pets', 'Lizard'),
  ('Pets', 'Tarantula'),
  ('Pets', 'Boyfriends'),
  ('Pets', 'Horse'),
  ('Pets', 'Rat'),
  ('Pets', 'Hamster'),
  ('Phobias', 'Ghosts'),
  ('Phobias', 'Spiders'),
  ('Phobias', 'Monsters'),
  ('Phobias', 'Rats'),
  ('Phobias', 'Toilets'),
  ('Phobias', 'Snakes'),
  ('Phobias', 'Germs'),
  ('Phobias', 'Clowns'),
  ('Phobias', 'Needles'),
  ('Phobias', 'Dogs'),
  ('Phobias', 'Birds'),
  ('Phobias', 'Insects'),
  ('Phobias', 'Children'),
  ('Phobias', 'Shadows'),
  ('Phobias', 'Roller Coasters'),
  ('Phobias', 'Planes'),
  ('Rooms', 'Kitchen'),
  ('Rooms', 'Hallway'),
  ('Rooms', 'Greenhouse'),
  ('Rooms', 'Bedroom'),
  ('Rooms', 'Bathroom'),
  ('Rooms', 'Dining Room'),
  ('Rooms', 'Office'),
  ('Rooms', 'Living Room'),
  ('Rooms', 'Attic'),
  ('Rooms', 'Basement'),
  ('Rooms', 'Porch'),
  ('Rooms', 'Nursery'),
  ('Rooms', 'Den'),
  ('Rooms', 'Bunker'),
  ('Rooms', 'Shed'),
  ('Rooms', 'Garage'),
  ('School Subjects', 'Math'),
  ('School Subjects', 'Chemistry'),
  ('School Subjects', 'Physics'),
  ('School Subjects', 'Biology'),
  ('School Subjects', 'History'),
  ('School Subjects', 'Philosophy'),
  ('School Subjects', 'Geography'),
  ('School Subjects', 'English'),
  ('School Subjects', 'Economics'),
  ('School Subjects', 'Spanish'),
  ('School Subjects', 'Art'),
  ('School Subjects', 'Music'),
  ('School Subjects', 'Gym'),
  ('School Subjects', 'Latin'),
  ('School Subjects', 'Religion'),
  ('School Subjects', 'Technology'),
  ('Sports', 'Football'),
  ('Sports', 'Soccer'),
  ('Sports', 'Golf'),
  ('Sports', 'Baseball'),
  ('Sports', 'Basketball'),
  ('Sports', 'Ice Hockey'),
  ('Sports', 'Sailing'),
  ('Sports', 'Squash'),
  ('Sports', 'Tennis'),
  ('Sports', 'Badminton'),
  ('Sports', 'Rock Climbing'),
  ('Sports', 'Wrestling'),
  ('Sports', 'Lacrosse'),
  ('Sports', 'Volleyball'),
  ('Sports', 'Triathlon'),
  ('Sports', 'Cycling'),
  ('States', 'California'),
  ('States', 'Texas'),
  ('States', 'Alabama'),
  ('States', 'Hawaii'),
  ('States', 'Florida'),
  ('States', 'Montana'),
  ('States', 'Nevada'),
  ('States', 'Mississippi'),
  ('States', 'North Carolina'),
  ('States', 'New York'),
  ('States', 'Kentucky'),
  ('States', 'Tennessee'),
  ('States', 'Colorado'),
  ('States', 'Washington'),
  ('States', 'Illinois'),
  ('States', 'Alaska'),
  ('Superheroes', 'Wonder Woman'),
  ('Superheroes', 'Spiderman'),
  ('Superheroes', 'Ironman'),
  ('Superheroes', 'Captain America'),
  ('Superheroes', 'The Flash'),
  ('Superheroes', 'Wolverine'),
  ('Superheroes', 'Green Lantern'),
  ('Superheroes', 'Groot'),
  ('Superheroes', 'The Incredibles'),
  ('Superheroes', 'Batman'),
  ('Superheroes', 'Scarlet Witch'),
  ('Superheroes', 'The Incredible Hulk'),
  ('Superheroes', 'Black Widow'),
  ('Superheroes', 'Powerpuff Girls'),
  ('Superheroes', 'Power Rangers'),
  ('Superheroes', 'Superman'),
  ('The Arts', 'Painting'),
  ('The Arts', 'Sculpture'),
  ('The Arts', 'Architecture'),
  ('The Arts', 'Dance'),
  ('The Arts', 'Literature'),
  ('The Arts', 'Opera'),
  ('The Arts', 'Stand-up'),
  ('The Arts', 'Comic Books'),
  ('The Arts', 'Illustration'),
  ('The Arts', 'Music'),
  ('The Arts', 'Theatre'),
  ('The Arts', 'Cinema'),
  ('The Arts', 'Video Games'),
  ('The Arts', 'Graffiti'),
  ('The Arts', 'Fashion'),
  ('The Arts', 'Photography'),
  ('Toys', 'Lego'),
  ('Toys', 'Rocking Horse'),
  ('Toys', 'Super Soaker'),
  ('Toys', 'Cabbage Patch Dolls'),
  ('Toys', 'Rubik''s Cube'),
  ('Toys', 'Etch a Sketch'),
  ('Toys', 'Teddy Bear'),
  ('Toys', 'Play Doh'),
  ('Toys', 'Yo-yo'),
  ('Toys', 'Frisbee'),
  ('Toys', 'Hot Wheels'),
  ('Toys', 'Barbie'),
  ('Toys', 'Slinky'),
  ('Toys', 'G.I. Joe'),
  ('Toys', 'Hula Hoop'),
  ('Toys', 'Furby'),
  ('Transport', 'Plane'),
  ('Transport', 'Car'),
  ('Transport', 'Tank'),
  ('Transport', 'Helicopter'),
  ('Transport', 'Cruise Ship'),
  ('Transport', 'Hovercraft'),
  ('Transport', 'Motorbike'),
  ('Transport', 'Bus'),
  ('Transport', 'Segway'),
  ('Transport', 'Cable Car'),
  ('Transport', 'Jet Ski'),
  ('Transport', 'Hot Air Balloon'),
  ('Transport', 'Train'),
  ('Transport', 'Spaceship'),
  ('Transport', 'Magic Carpet'),
  ('Transport', 'Broomstick'),
  ('Video Games', 'Zelda'),
  ('Video Games', 'Mario'),
  ('Video Games', 'Pong'),
  ('Video Games', 'Tetris'),
  ('Video Games', 'Farmville'),
  ('Video Games', 'Sims'),
  ('Video Games', 'Zoo Tycoon'),
  ('Video Games', 'Animal Crossing'),
  ('Video Games', 'Minecraft'),
  ('Video Games', 'Minesweeper'),
  ('Video Games', 'Solitaire'),
  ('Video Games', 'Wii Sports'),
  ('Video Games', 'Pinball'),
  ('Video Games', 'Pokemon'),
  ('Video Games', 'Sonic the Hedgehog'),
  ('Video Games', 'Donkey Kong'),
  ('World Wonders', 'Pyramids'),
  ('World Wonders', 'Eiffel Tower'),
  ('World Wonders', 'Statue of Liberty'),
  ('World Wonders', 'Grand Canyon'),
  ('World Wonders', 'Stonehenge'),
  ('World Wonders', 'Golden Gate Bridge'),
  ('World Wonders', 'Colosseum'),
  ('World Wonders', 'Sydney Opera House'),
  ('World Wonders', 'Christ the Redeemer'),
  ('World Wonders', 'Machu Picchu'),
  ('World Wonders', 'Taj Mahal'),
  ('World Wonders', 'Hoover Dam'),
  ('World Wonders', 'Great Wall of China'),
  ('World Wonders', 'Great Barrier Reef'),
  ('World Wonders', 'Empire State Building'),
  ('World Wonders', 'Leaning Tower of Pisa'),
  ('Zoo', 'Elephant'),
  ('Zoo', 'Giraffe'),
  ('Zoo', 'Koala'),
  ('Zoo', 'Tiger'),
  ('Zoo', 'Lion'),
  ('Zoo', 'Leopard'),
  ('Zoo', 'Meerkat'),
  ('Zoo', 'Buffalo'),
  ('Zoo', 'Ostrich'),
  ('Zoo', 'Owl'),
  ('Zoo', 'Eagle'),
  ('Zoo', 'Parrot'),
  ('Zoo', 'Scorpion'),
  ('Zoo', 'Alligator'),
  ('Zoo', 'Zebra'),
  ('Zoo', 'Gorilla');
